apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: modelbricks

images:
- name: ghcr.io/virtualcell/modelbricks
  newTag: 0ef13e0

replicas:
- count: 1
  name: modelbricks

resources:
- modelbricks-ingress.yaml
- secret-ghcr.yaml
- ../../base
