---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: modelbricks
spec:
  encryptedData:
    .dockerconfigjson: AgAOxD8yANeoHBpMoKkIJ+2uZmyAZXE2aFs+bGXmUEvAhzEEbtiSapqlS2nSkHc2fq9hMPuGD05V+SvaHFGrlapkRMqfMAybnWDOpO3G9lbed+m+eM0vkO1NQNWd97NJWHfGRvHvRl1p5r0Rg6gs2S8gQpe7naPpNrd79gRRGevZzIgYBKCJ++OaaBHSIU+1NQBO7/1izbppyyq48BRcaLt07HVjkrUQKGWiAqXeoBySchQFn4SjtHyT2cc4LUzx12vMchTsohM/Anv2K68sXqpQWzMt29/0zBtogE8OF7uaQmmzdy9lHcgqa9/Ld0BKVEe35Z6WPZ1tXkfagiEfiNuWGS0lbXttl2Bvfh2FQPBu6AbXnZjNqJdOD/MU8p7FmBbp7oi67VmAEO1ERg77Kzoo2faN8BWsbptipH9gOUFxS88SdsALabGPY/yyooqs651G3ygg00cTLoQLoc9DpXOSm0K+PVjOTt7hTu3TLUjhEBZrZp5uWcWYZilI2VIECPQ4NodZm/3bnDk6luBAO4CZNlDrMY7WOPbhpbuF+lLglfQuuRAauAFp+3Jp3v44On1MBHtqrQsj0db2OOBpGGvS+JsBbgxR9Jz94eCcym+Cjyy+7rkXBZEV5NbPqZMwGkN2Z0iP0EJUzM5Pt9iDqkdYp5S3YhdX+wKBlWI2KQg+sUTDvqfYYscjBclqhuluyT8neoR532ZAmsHsyfazf2ORW6jPqdbmh2CQ7/xEO5roGCR393CCmJ6swcN5DX/YmdfWxCwKu1FYC0LmyQnnw336LNylL3S56p7O1xKpLdR0lYnM3fLJ8qZHPqGnaa4zBS3Snjy5SpKsKGd8B0n7tO1NndIrOFlbJYos0HW9n/QJli1Jk5pV0IFhTPQ4OnjNbg4txQLdE5RQWl2fKPSx/u4F6J6DZOSjlz0attsn78mae09Loce03vC5dl8vZhY0UJ2OJlpUQS/HMY0lgFf6ceeU
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: modelbricks
    type: kubernetes.io/dockerconfigjson
